services:
  web:
    image: diplom:1
    command: python manage.py runserver
    volumes:
      - .:/code
    ports:
      - "${HOST_PORT}:8000"
    env_file:
      - .env
    working_dir: /code
    restart: unless-stopped

  migrations:
    image: diplom:1
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py migrate
    env_file:
      - .env
    volumes:
      - .:/code
    working_dir: /code