# Generated by Django 5.2.1 on 2025-06-22 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0003_alter_club_leader_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('file', models.FileField(upload_to='club_materials/', verbose_name='Файл')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='main.club')),
            ],
            options={
                'verbose_name': 'Материал клуба',
                'verbose_name_plural': 'Материалы клубов',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
