# Generated by Django 5.2.1 on 2025-06-22 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_club_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='leader_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='ФИО руководителя'),
        ),
    ]
