# Generated by Django 5.2.1 on 2025-06-18 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL-идентификатор')),
                ('content', models.TextField(verbose_name='Содержимое')),
                ('news_type', models.CharField(choices=[('event', 'Мероприятие'), ('report', 'Отчет'), ('achievement', 'Достижение'), ('announcement', 'Объявление')], default='announcement', max_length=20, verbose_name='Тип')),
                ('image', models.ImageField(blank=True, upload_to='news/', verbose_name='Изображение')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_items', to='main.club', verbose_name='Кружок/Студия')),
            ],
            options={
                'verbose_name': 'Новость/Мероприятие',
                'verbose_name_plural': 'Новости и мероприятия',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
